### ISSUE TITLE
Github entries are not working

### ISSUE THREAD

**Issue by roland-d** [tomhunter-gh/SourceLog#22]
Hello Tom,

Since the last update I am having some issues:
1. The update lost all my repo entries
2. Github entries no longer seem to work.

I have chosen type Github and the URL is set to https://github.com/tomhunter-gh/SourceLog but I don't get any updates.

**Comment by tomhunter-gh** [comment]
Unfortunately I haven’t completely figured out EF code first migrations yet so the SQL Server Compact database used to store the data is wiped with the recent update – this means you have to re-add subscriptions.  I hope to be able to maintain subscriptions with future upgrades (I know it’ll be pretty annoying otherwise!).

The application currently logs event information to a text file stored under the following directory:

WinXP: C:\Documents and Settings<user>\Application Data\SourceLog\
Win7/8: C:\Users<user>\AppData\Roaming\SourceLog

Could you check the log file and let me know if it has any further information?

Thanks

**Comment by roland-d** [comment]
Hello Tom,

Did you get my email with the application logs?

**Comment by tomhunter-gh** [comment]
I did - thanks a lot.  I just haven't had a chance to look into this yet properly as I've been away on Holiday.  I'll get this fixed as soon as I can.

**Comment by roland-d** [comment]
No worries, was just wondering since I didn't see or hear anything after sending them :)
